# Generated by Django 5.1.6 on 2025-05-01 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0001_initial'),
    ]

    operations = [
    ]
