# Generated by Django 5.1.6 on 2025-05-01 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0002_auto_20250501_1945'),
    ]

    operations = [
    ]
