# Generated by Django 5.1.6 on 2025-05-01 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0003_auto_20250501_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventregistration',
            name='event_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
