# Generated by Django 5.1.6 on 2025-05-01 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0004_eventregistration_event_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventregistration',
            name='event_time',
        ),
    ]
