# Generated by Django 5.1.6 on 2025-05-01 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0005_remove_eventregistration_event_time'),
    ]

    operations = [
    ]
