# Generated by Django 5.1.6 on 2025-05-01 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0006_migrate_event_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventregistration',
            name='event_datetime',
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='event_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='event_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
