# Generated by Django 5.1.6 on 2025-05-02 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0007_remove_eventregistration_event_datetime_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memberprofile',
            name='has_paid',
        ),
    ]
