# Generated by Django 5.1.6 on 2025-05-02 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0009_memberprofile_has_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memberprofile',
            name='has_paid',
        ),
    ]
