# Generated by Django 5.1.6 on 2025-05-02 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0010_remove_memberprofile_has_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberprofile',
            name='has_paid',
            field=models.BooleanField(default=False),
        ),
    ]
