# Generated by Django 5.1.6 on 2025-05-08 09:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0011_memberprofile_has_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
