# Generated by Django 5.1.6 on 2025-05-11 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0012_blogs_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_name',
            field=models.CharField(max_length=50, verbose_name='Event Name'),
        ),
    ]
