# Generated by Django 5.1.6 on 2025-04-03 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(default='default@example.com', max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('event_name', models.CharField(max_length=200)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
